---
apiVersion: batch/v1
kind: Job
metadata:
  name: job-datamart
  namespace: default
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: datamart
          image: datamart:latest
          imagePullPolicy: Never
          env:
            - name: MONGO_URI
              value: "mongodb://mongodb:27017/"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"
